spring:
  datasource:
    url: jdbc:mysql://localhost:3306/health_
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 0112

  #redis数据源
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0

#项目端口和路径
server:
  port: 80
  context-path: /

#mapper路径
mapper:
  mappers: com.xust.healthotwechat.entity









